name: hello workflow
on:
  push:
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: say hello
        run: echo "Hello from GitHub Actions!"

      - name: print date time
        run: date

      - name: print branch name
        run: echo "Branch name is ${{ github.ref_name }}"

      - name: print list the files
        run: ls -la

      - name: print runnner os
        run: echo "Runner OS is $RUNNER_OS"
