name: hello workflow
on:
  push:
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: say hello
        run: echo "Hello from GitHub Actions!"
