name: Main Pipeline

on:
  push:
    branches: [main]

jobs:
  # 1. First, run your Build & Test
  call-build-and-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      python_version: '3.10'
      run_tests: true

  # 2. Then, Build & Push Docker Image (Only if tests pass)
  deploy-docker:
    needs: call-build-and-test
    if: needs.call-build-and-test.outputs.test_result == 'passed'
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: 'fastapi-capstone'
      tag: 'latest'
    secrets:
      docker_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_token: ${{ secrets.DOCKER_HUB_TOKEN }}

  # 3. Optional: Check the final output
  final-check:
    needs: deploy-docker
    runs-on: ubuntu-latest
    steps:
      - name: Show Image URL
        run: | 
            echo "Deployed to: ${{ needs.deploy-docker.outputs.image_url }}"
