name: Main Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    # types: [opened, synchronize]

jobs:
  # 1. First, run your Build & Test
  call-build-and-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      python_version: '3.10'
      run_tests: true

  # 2. Then, Build & Push Docker Image (Only if tests pass)
  deploy-docker:
    needs: call-build-and-test
    if: needs.call-build-and-test.outputs.test_result == 'passed'
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: 'fastapi-capstone'
      tag: "sha-${{ github.sha }}"
    secrets:
      docker_username: ${{ vars.DOCKER_USERNAME }}
      docker_token: ${{ secrets.DOCKER_TOKEN }}

  # 3. Optional: Check the final output
  deploy-prod:
    needs: deploy-docker
    runs-on: ubuntu-latest
    environment: production  # This triggers protection rules/manual approval
    steps:
      - name: Deploying to Production
        run: |
          echo "Deploying image: ${{ needs.deploy-docker.outputs.image_url }} to production"
          echo "Deployment status: Success"