name: PR Check
on:
  pull_request:
    branches: main
    types:
      - opened
      - synchronize
jobs:
  pr_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print PR branch name
        run: |
          echo PR check running for branch: ${{ github.head_ref }}
