name: Reusable Docker Build & Push

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the Docker image (e.g., my-app)'
        required: true
        type: string
      tag:
        description: 'Tag for the image (e.g., latest or v1.0.0)'
        required: false
        default: 'latest'
        type: string
    secrets:
      docker_username:
        required: true
      docker_token:
        required: true
    outputs:
      image_url:
        description: "The full URL of the pushed image"
        value: ${{ jobs.docker-push.outputs.full_url }}

jobs:
  docker-push:
    runs-on: ubuntu-latest
    outputs:
      full_url: ${{ steps.set-url.outputs.url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.docker_username }}
          password: ${{ secrets.docker_token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.docker_username }}/${{ inputs.image_name }}:${{ inputs.tag }}

      - name: Set Image URL Output
        id: set-url
        run: |
          FULL_URL="${{ vars.docker_username }}/${{ inputs.image_name }}:${{ inputs.tag }}"
          echo "url=$FULL_URL" >> $GITHUB_OUTPUT
          echo "Image successfully pushed to: $FULL_URL"
