name: Secrets Demo
on:
    workflow_dispatch:

jobs:
    check-secret:
        runs-on: ubuntu-latest

        steps:
            - name: check secrete variable
              run: |
                if [ -n "${{secrets.MY_SECRET_MESSAGE}}" ]; then
                    echo "The secret is set: true"
                else
                    echo "The secret is set: false"
                fi
            - name: Attempt to print secret
              run: |
                echo "Secret value: ${{ secrets.MY_SECRET_MESSAGE }}" 