name: Run Tests

on:
    workflow_dispatch:

jobs:
    run_first_workflow:
        runs-on: ubuntu-latest
        steps:
            - name: test job run
              run: |
                echo job run success
