name: Test Setup and Greet Action

on:
  workflow_dispatch:
    # branches:
    #   - main

jobs:
  greet-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run custom greet action
        id: run-greet-action
        uses: ./.github/actions/setup-and-greet
        with:
          name: "Alice"
          language: "fr"

      - name: Show greeted output
        run: | 
            echo "Greeted: ${{ steps.run-greet-action.outputs.greeted }}"